### PR TITLE
Abort pending partial submissions on submit

### LINKED ISSUE #14: Partial submissions are not removed after submissions
Steps to reproduce:
1. Complete the form
2. Edit the page in the CMS and check the entries under Partial Submissions tab

The submission should be removed from the Partial Submissions tab.

### PR DESCRIPTION
**Pull request by lhalaa**
Fixes https://github.com/Firesphere/silverstripe-partial-userforms/issues/14

### CODE REVIEW

File: client/src/js/partialuserforms/partialsubmission.js [hunk 1]
```diff
@@ -54,4 +58,23 @@ const attachSubmitPartial = (button) => {
 
 export default function () {
   buttons().forEach(attachSubmitPartial);
+
+  // Clear all pending partial submissions on submit
+  const form = document.body.querySelector('form.userform');
```
Comment (Firesphere) [inline client/src/js/partialuserforms/partialsubmission.js]: Could you extract this to a separate method and have the `const` at the top, in line with how most of the code is handled

**Review by Firesphere — CHANGES_REQUESTED** [review]

File: src/extensions/SubmittedFormExtension.php [hunk 2]
```diff
@@ -23,12 +23,14 @@ public function updateAfterProcess()
...
         $partialID = Controller::curr()->getRequest()->getSession()->get(PartialSubmissionController::SESSION_KEY);
-        /** @var PartialFormSubmission $partialForm */
-        $partialForm = PartialFormSubmission::get()->byID($partialID);
-        if ($partialForm) {
-            $partialForm->delete();
-            $partialForm->destroy();
+        if ($partialID !== null) {
+            /** @var PartialFormSubmission $partialForm */
+            $partialForm = PartialFormSubmission::get()->byID($partialID);
+            if ($partialForm) {
```
Comment (Firesphere) [inline src/extensions/SubmittedFormExtension.php]: These two ifs can be combined in to one:
`if ($partialID !== null && ($partialForm = $partialFormSubmission::get()->byID($partialID))) {`

It would save a nested if.
Or, maybe even simpler, 
`($partialForm = $partialFormSubmission::get()->byID((int)$partialID))`
If the partialID is `null`, it would become 0, and thus not finding anything. If the partialID doesn't exist, it would still work.

**Review by Firesphere — COMMENTED** [review]
Only a comment I'd like to have a yak about, nothing big

File: src/extensions/SubmittedFormExtension.php (hunk 2 above)
Comment (lhalaa) [reply src/extensions/SubmittedFormExtension.php]: Well, I want to avoid conditional assignments as much as I can. How about early return? But then there will be 2 returns for this case.

Comment (lhalaa) [reply src/extensions/SubmittedFormExtension.php]:
```
$partialID = Controller::curr()->getRequest()->getSession()->get(PartialSubmissionController::SESSION_KEY);
if ($partialID === null) {
    return;
}

/** @var PartialFormSubmission $partialForm */
$partialForm = PartialFormSubmission::get()->byID($partialID);
if ($partialForm === null) {
    return;
}

$partialForm->delete();
$partialForm->destroy();
Controller::curr()->getRequest()->getSession()->clear(PartialSubmissionController::SESSION_KEY);
```

Comment (Firesphere) [reply src/extensions/SubmittedFormExtension.php]: I prefer the last idea, I like early returns and verbosity :)

Comment (lhalaa) [reply src/extensions/SubmittedFormExtension.php]: @Firesphere ready for PR

**Review by Firesphere — APPROVED** [review]
